pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.dji.com/nexus/repository/maven-public/' }
    }
}
rootProject.name = 'DachmanDroneDirector'
include ':app'
