platform :ios, '16.0'

project 'DachmanDroneDirector.xcodeproj'

target 'DachmanDroneDirector' do
  pod 'DJI-SDK-iOS', '4.16.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
